# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Viterbi Algorithm for Symmetric Continuous-time HMM (Rcpp)
#'
#' This function implements a Viterbi algorithm for the continuous-time Hidden Markov Model in a specific condition: n uniform initial states and a special-case dual transition probabilities related to the timestamp and parameter theta (detailed formula in the pdf instruction). The input arguments include the timestamps of each observation represented in a row with size m, a transition parameter theta used for the definition of the transition probabilities, a matrix containing all the conditional probabilities for each observation given each state at that timestamp. Note the time complexity is O(mn).
#'
#' @param ts size m positive float values characterize the timestamps for the observations
#' @param theta a single float value as the tansition parameter determining the transition probabilities
#' @param obs size n*m matrix containing all the conditional probabilities for each observation given each state at that timestamp.
#' @return vector of Viterbi path representing the most likely state at each timestamp with observation
#' @examples
#' obs <- matrix(c(0.88,0.10,0.88,0.10,0.02,0.30,0.02,0.30,0.10,0.60),2,5)
#' theta <- log(2)
#' ts <- c(1,2,3,4,5)
#' ctmcViterbi(ts, theta, obs)
#'
#' ts <- c(1,2.95,3,4,5)
#' ctmcViterbi(ts, theta, obs)
#'
#' @export
ctmcViterbi <- function(ts, theta, obs) {
    .Call('_tonytianHW4_ctmcViterbi', PACKAGE = 'tonytianHW4', ts, theta, obs)
}

#' Forward-backward Algorithm for Symmetric Continuous-time HMM (Rcpp)
#'
#' This function implements the forward-backward algorithm for the continuous-time Hidden Markov Model in a specific condition: n uniform initial states and a special-case dual transition probabilities related to the timestamp and parameter theta (detailed formula in the pdf instruction). The input arguments include the timestamps of each observation represented in a row with size m, a transition parameter theta used for the definition of the transition probabilities, a matrix containing all the conditional probabilities for each observation given each state at that timestamp. Note the time complexity is O(mn).
#'
#' @param ts size m positive float values characterize the timestamps for the observations
#' @param theta a single float value as the tansition parameter determining the transition probabilities
#' @param obs size n*m matrix containing all the conditional probabilities for each observation given each state at that timestamp.
#' @return m*n matrix containing all the conditional probabilities of each state at the timestamps given the observations
#' @examples
#' obs <- matrix(c(0.88,0.10,0.88,0.10,0.02,0.30,0.02,0.30,0.10,0.60),2,5)
#' theta <- log(2)
#' ts <- c(1,2,3,4,5)
#' ctmcForwardBackward(ts, theta, obs)
#'
#' ts <- c(1,2.95,3,4,5)
#' ctmcForwardBackward(ts, theta, obs)
#'
#' @export
ctmcForwardBackward <- function(ts, theta, obs) {
    .Call('_tonytianHW4_ctmcForwardBackward', PACKAGE = 'tonytianHW4', ts, theta, obs)
}

